/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.jvnet.substance.SubstanceLookAndFeel;
import util.ContadorPanelActividad;
import view.OC.vtnListarCompras;
import view.OC.vtnOD;
import view.almacen.vtnAjustes;
import view.almacen.vtnIngresoalmacen;
import view.almacen.vtnInventarioInicial;
import view.almacen.vtnKardex;
import view.almacen.vtnKardexInventario;
import view.licencias.vtnAcercade;
import view.reporteCompras.vtnReporteCompras;
import view.usuarios.vtnUsuarios;
import view.usuarios.vtngestionPersmisos;
import view.ventas.vtnComboProducto;
import view.ventas.vtnDefinicionPrecios;
import view.ventas.vtnVentas;

/**
 *
 * @author Reynaldo
 */
public class vtnPrincipal extends javax.swing.JFrame {

    public vtnPrincipal() {

        //vtnPrincipal.setDefaultLookAndFeelDecorated(true);
        //SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenSkin");
        initComponents();
        //Insertando la fecha
        Calendar ca = Calendar.getInstance();
        int año = ca.get(Calendar.YEAR);
        int mes = ca.get(Calendar.MONTH) + 1;
        int dia = ca.get(Calendar.DAY_OF_MONTH);
        String fecha = dia + "-" + mes + "-" + año;
        lbmFecha.setText(fecha);
        //fin insercion fecha

        ContadorPanelActividad.contadorOC();//llamando al panel de actividades
        ContadorPanelActividad.contadorIA();//llamando al panel de actividades

        atajosTeclado();//iniciando el modulo de atajos de teclado

    }

    //Metodo que agrega atajos de teclado al menu item y a la palicacion
    public void atajosTeclado() {
        MitemOC.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.CTRL_DOWN_MASK));
        MitemOCprocesar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_P, InputEvent.CTRL_DOWN_MASK));
    }

    public static void contadorOC(String contador) {
        labelContadorOC.setText(contador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sysMDI = new javax.swing.JDesktopPane();
        panelActividad = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbmAvatar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbmFecha = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelContadorOC = new javax.swing.JLabel();
        panelRound2 = new org.edisoncor.gui.panel.PanelRound();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        jLabel7 = new javax.swing.JLabel();
        labelContadorIA = new javax.swing.JLabel();
        panelRound3 = new org.edisoncor.gui.panel.PanelRound();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        MitemOCprocesar = new javax.swing.JMenuItem();
        MitemOC = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas e Inventarios");

        panelActividad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de actividad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 0, 51))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Privilegio:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbmAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbmAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha:");

        lbmFecha.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbmFecha.setText("XXXXXXXXXX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbmFecha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbmFecha))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelRound1.setForeground(new java.awt.Color(0, 102, 204));
        panelRound1.setToolTipText("Ordenes de compra a procesar");
        panelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound1MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OCProcesar.png"))); // NOI18N

        labelMetric1.setText("OC a procesar");
        labelMetric1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        labelContadorOC.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelContadorOC.setForeground(new java.awt.Color(0, 153, 51));
        labelContadorOC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContadorOC.setText("0");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                            .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                            .addComponent(labelContadorOC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContadorOC)
                .addContainerGap())
        );

        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        labelMetric2.setText("Ingreso Almacen");
        labelMetric2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ingresoAlmacen.png"))); // NOI18N

        labelContadorIA.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelContadorIA.setForeground(new java.awt.Color(0, 153, 51));
        labelContadorIA.setText("0");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(labelContadorIA)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContadorIA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelMetric3.setText("Ventas");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ventas2.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clockFace1.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelActividadLayout = new javax.swing.GroupLayout(panelActividad);
        panelActividad.setLayout(panelActividadLayout);
        panelActividadLayout.setHorizontalGroup(
            panelActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActividadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelActividadLayout.setVerticalGroup(
            panelActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActividadLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sysMDILayout = new javax.swing.GroupLayout(sysMDI);
        sysMDI.setLayout(sysMDILayout);
        sysMDILayout.setHorizontalGroup(
            sysMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sysMDILayout.createSequentialGroup()
                .addContainerGap(625, Short.MAX_VALUE)
                .addComponent(panelActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        sysMDILayout.setVerticalGroup(
            sysMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysMDILayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sysMDI.setLayer(panelActividad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(sysMDI, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/archivo.png"))); // NOI18N
        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/users.png"))); // NOI18N
        jMenu2.setText("Usuarios");

        jMenuItem1.setText("Crear usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem18.setText("Gestionar permisos");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/categoria.png"))); // NOI18N
        jMenu3.setText("Categorias");

        jMenuItem2.setText("altas/bajas/cambios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/ventas.png"))); // NOI18N
        jMenu7.setText("Ventas");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/menu/Dollar.png"))); // NOI18N
        jMenuItem9.setText("Venta/Salida");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/menu/Buy.png"))); // NOI18N
        jMenuItem10.setText("Armar combo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem20.setText("Definir lista precios");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem20);

        jMenuBar1.add(jMenu7);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/producto.png"))); // NOI18N
        jMenu4.setText("Productos");

        jMenuItem3.setText("Gestión de productos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem19.setText("Listar productos");
        jMenu4.add(jMenuItem19);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/proveedor.png"))); // NOI18N
        jMenu5.setText("Proveedores");

        jMenuItem4.setText("Gestión de proveedores");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem17.setText("Listado de proveedores");
        jMenu5.add(jMenuItem17);

        jMenuBar1.add(jMenu5);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/house.png"))); // NOI18N
        jMenu8.setText("Almacen");

        jMenuItem6.setText("Gestión de almacen");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem6);

        jMenuItem7.setText("Ingreso Almacen");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuItem8.setText("Inventario");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuItem12.setText("Kardex Inventario");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenu10.setText("Operaciones inventarios");

        jMenuItem14.setText("Inventario inicial");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem14);

        jMenuItem15.setText("Ajustes inventario");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem15);

        jMenu8.add(jMenu10);

        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/compras.png"))); // NOI18N
        jMenu9.setText("Compras");

        MitemOCprocesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/menu/Notes.png"))); // NOI18N
        MitemOCprocesar.setText("OC a procesar");
        MitemOCprocesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitemOCprocesarActionPerformed(evt);
            }
        });
        jMenu9.add(MitemOCprocesar);

        MitemOC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/menu/Shopping cart.png"))); // NOI18N
        MitemOC.setText("Crear OC");
        MitemOC.setToolTipText("Crear Orden de compra");
        MitemOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitemOCActionPerformed(evt);
            }
        });
        jMenu9.add(MitemOC);

        jMenuItem11.setText("Reportes");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem11);

        jMenuBar1.add(jMenu9);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/configuracion.png"))); // NOI18N
        jMenu6.setText("Configuraciones");

        jMenuItem5.setText("Gestionar configuración");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/help_32.png"))); // NOI18N
        jMenu11.setText("Acerca de..");

        jMenuItem13.setText("Licencia");
        jMenu11.add(jMenuItem13);

        jMenuItem16.setText("Acerca de..");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem16);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        vtnCategorias cate = new vtnCategorias();
        cate.setTitle("Gestión de categorias");
        cate.setResizable(false);//no es redimencionable
        cate.setMaximizable(false);//no se puede maximizar
        cate.setClosable(true);//si se puede cerra la ventana
        cate.setIconifiable(true);
        sysMDI.add(cate);
        cate.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        String varValidacion = vtnProducto.validaVentana;
        if (varValidacion == null) {

            vtnProducto pro = new vtnProducto();
            pro.setTitle("Gestión de productos");
            pro.setResizable(false);//no es redimencionable
            pro.setMaximizable(false);//no se puede maximizar
            pro.setClosable(true);//si se puede cerra la ventana
            pro.setIconifiable(true);
            sysMDI.add(pro);
            pro.setVisible(true);
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "La ventana gestión de de productos\nya esa activa..!!", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnProveedor.validaVentana;
        if (varValidacion == null) {
            vtnProveedor alm = new vtnProveedor();
            alm.setTitle("Gestión de proveedores");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            //alm.setIconifiable(true);
            sysMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Gestión de de proveedores\nya esa activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        vtnInformacion info = new vtnInformacion();
        info.setTitle("Información");
        info.setResizable(false);//no es redimencionable
        info.setMaximizable(false);//no se puede maximizar
        info.setClosable(true);//si se puede cerra la ventana
        info.setIconifiable(true);
        sysMDI.add(info);
        info.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnAlmacen.validaVentana;
        if (varValidacion == null) {

            vtnAlmacen alm = new vtnAlmacen();
            alm.setTitle("Gestion de almacen..");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            alm.setIconifiable(true);
            sysMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Gestión de Almacen\nya esa activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnIngresoalmacen.validaVentana;
        if (varValidacion == null) {
            vtnIngresoalmacen almigr = new vtnIngresoalmacen();
            almigr.setTitle("Ingreso almacen");
            almigr.setResizable(false);//no es redimencionable
            almigr.setMaximizable(false);//no se puede maximizar
            almigr.setClosable(true);//si se puede cerra la ventana
            almigr.setIconifiable(true);
            sysMDI.add(almigr);
            almigr.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Generar Orden de compra\nya esa habierta..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void MitemOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitemOCActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnOD.validaVentana;
        if (varValidacion == null) {
            vtnOD alm = new vtnOD();
            alm.setTitle("Crear Orden de compra");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            //alm.setIconifiable(true);
            sysMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Generar Orden de compra\nya esa activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MitemOCActionPerformed

    private void MitemOCprocesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitemOCprocesarActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnListarCompras.validaVentana;
        if (varValidacion == null) {
            vtnListarCompras alm = new vtnListarCompras();
            alm.setTitle("Listado de compras");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            // alm.setIconifiable(true);
            sysMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Listado de compras\nya esa activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MitemOCprocesarActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnReporteCompras.validaVentana;
        if (varValidacion == null) {
            vtnReporteCompras repcompras = new vtnReporteCompras();
            repcompras.setTitle("Reporte compras");
            repcompras.setResizable(false);//no es redimencionable
            repcompras.setMaximizable(false);//no se puede maximizar
            repcompras.setClosable(true);//si se puede cerra la ventana
            //repcompras.setIconifiable(true);
            sysMDI.add(repcompras);
            repcompras.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana reporte compras\nya esa activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnKardexInventario.validaVentana;
        if (varValidacion == null) {
            vtnKardexInventario kardexInventario = new vtnKardexInventario();
            kardexInventario.setTitle("Inventario almacen");
            kardexInventario.setResizable(false);//no es redimencionable
            kardexInventario.setMaximizable(false);//no se puede maximizar
            kardexInventario.setClosable(true);//si se puede cerra la ventana
            kardexInventario.setIconifiable(true);
            sysMDI.add(kardexInventario);
            kardexInventario.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Inventario\nya esa activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnKardex.validaVentana;
        if (varValidacion == null) {
            vtnKardex kardex = new vtnKardex();
            kardex.setTitle("Kardex de Almacen");
            kardex.setResizable(false);//no es redimencionable
            kardex.setMaximizable(false);//no se puede maximizar
            kardex.setClosable(true);//si se puede cerra la ventana
            kardex.setIconifiable(true);
            sysMDI.add(kardex);
            kardex.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Kardex de Almacen\nya esta activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:

        String varValidacion = vtnAjustes.validaVentana;
        if (varValidacion == null) {
            vtnAjustes almigr = new vtnAjustes();
            almigr.setTitle("Ajustes Almacen");
            almigr.setResizable(false);//no es redimencionable
            almigr.setMaximizable(false);//no se puede maximizar
            almigr.setClosable(true);//si se puede cerra la ventana
            almigr.setIconifiable(true);
            sysMDI.add(almigr);
            almigr.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Ajustes Inventario\nya esta activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String varValidacion = vtnInventarioInicial.validaVentana;
        if (varValidacion == null) {
            vtnInventarioInicial almigr = new vtnInventarioInicial();
            //  almigr.setTitle("Ajustes Almacen");
            almigr.setResizable(false);//no es redimencionable
            almigr.setMaximizable(false);//no se puede maximizar
            almigr.setClosable(true);//si se puede cerra la ventana
            almigr.setIconifiable(true);
            sysMDI.add(almigr);
            almigr.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Inventario inicial\nya esta activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnAcercade.validaVentana;
        if (varValidacion == null) {
            vtnAcercade almigr = new vtnAcercade();
            //almigr.setTitle("Ajustes Almacen");
            almigr.setResizable(false);//no es redimencionable
            almigr.setMaximizable(false);//no se puede maximizar
            almigr.setClosable(true);//si se puede cerra la ventana
            almigr.setIconifiable(false);
            sysMDI.add(almigr);
            almigr.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Acerca de..\nya esta activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void panelRound1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound1MousePressed
        // TODO add your handling code here:
        String varValidacion = vtnListarCompras.validaVentana;
        if (varValidacion == null) {
            vtnListarCompras alm = new vtnListarCompras();
            alm.setTitle("Listado de compras");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            alm.setIconifiable(true);
            sysMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Listado de compras\nya esa activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_panelRound1MousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnUsuarios.validaVentana;
        if (varValidacion == null) {
            vtnUsuarios alm = new vtnUsuarios();
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            alm.setIconifiable(true);
            sysMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Administración de usuarios\nya esa activa..!!", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtngestionPersmisos.validaVentana;
        if (varValidacion == null) {
            vtngestionPersmisos alm = new vtngestionPersmisos();
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            alm.setIconifiable(true);
            sysMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Gestión de Permisos\nya esa activa..!!", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        // TODO add your handling code here:
        String varValidacion = vtnIngresoalmacen.validaVentana;
        if (varValidacion == null) {
            vtnIngresoalmacen alm = new vtnIngresoalmacen();
            //alm.setTitle("Listado de compras");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            alm.setIconifiable(true);
            sysMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Ingreso almacen\nya esa activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_panelRound2MousePressed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        String varValidacion = vtnVentas.validaVentana;
        if (varValidacion == null) {
            vtnVentas ven = new vtnVentas();
            ven.setTitle("Ventas");
            ven.setResizable(false);//no es redimencionable
            ven.setMaximizable(false);//no se puede maximizar
            ven.setClosable(true);//si se puede cerra la ventana
            // alm.setIconifiable(true);
            sysMDI.add(ven);
            ven.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana ventas\nya esa activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnComboProducto.validaVentana;
        if (varValidacion == null) {
            vtnComboProducto ven = new vtnComboProducto();
            ven.setTitle("Armar combo producto");
            ven.setResizable(false);//no es redimencionable
            ven.setMaximizable(false);//no se puede maximizar
            ven.setClosable(true);//si se puede cerra la ventana
            ven.setIconifiable(true);
            sysMDI.add(ven);
            ven.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana armar combo producto\nya esa activa..!!", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String varValidacion = vtnDefinicionPrecios.validaVentana;
        if (varValidacion == null) {
            vtnDefinicionPrecios ven = new vtnDefinicionPrecios();
            ven.setTitle("Definicion de lista de precios");
            ven.setResizable(false);//no es redimencionable
            ven.setMaximizable(false);//no se puede maximizar
            ven.setClosable(true);//si se puede cerra la ventana
            // alm.setIconifiable(true);
            sysMDI.add(ven);
            ven.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Definir Lista de Precios\nya esa activa..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MitemOC;
    private javax.swing.JMenuItem MitemOCprocesar;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel labelContadorIA;
    public static javax.swing.JLabel labelContadorOC;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    public static javax.swing.JLabel lbmAvatar;
    public static javax.swing.JLabel lbmFecha;
    public static javax.swing.JPanel panelActividad;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    private org.edisoncor.gui.panel.PanelRound panelRound2;
    private org.edisoncor.gui.panel.PanelRound panelRound3;
    public static javax.swing.JDesktopPane sysMDI;
    // End of variables declaration//GEN-END:variables
}
