/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.almacen;

import dao.AjusteDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import util.tablakardex.CellRenderer;
import util.tablakardex.HeaderCellRenderer;
import view.vtnPrincipal;

/**
 *
 * @author Reynaldo
 */
public class vtnListarAjustes extends javax.swing.JInternalFrame {

    /**
     * Creates new form vtnListarAjustes
     */
    public static String validaVentana;

    public vtnListarAjustes() {
        initComponents();
        validaVentana = "x";//insertando un valor a la variable que valida a la ventana
        /*Poniendo el JinternalFrame al centro de la ventana*/
        int a = vtnPrincipal.sysMDI.getWidth() - this.getWidth();
        int b = vtnPrincipal.sysMDI.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);
        /*fin-----*/
        listarAjuste();
    }
    //Metodo que le da el estilo a la tabla
    public void estiloTabla(JTable tabla) 
    {
        //color de los bordes de las celdas
        tabla.setGridColor(new java.awt.Color(214, 213, 208));
        //tamaño de columnas
        tabla.getColumnModel().getColumn(0).setPreferredWidth(30);//columna id
        tabla.getColumnModel().getColumn(1).setPreferredWidth(150);//columna fecha
        tabla.getColumnModel().getColumn(2).setPreferredWidth(150);//Columna motivo
        tabla.getColumnModel().getColumn(3).setPreferredWidth(80);//Columna responsable
        tabla.getColumnModel().getColumn(4).setPreferredWidth(150);//Producto
      
        //altura de filas
        tabla.setRowHeight(24);
//
        JTableHeader jtableHeader = tabla.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderCellRenderer());
        tabla.setTableHeader(jtableHeader);
        //fin de la creacion del formato del kardex
    }

    //Metodo que realiza el listado de los datos en un JTable de java
    public void listarAjuste() 
    {
        try 
        {
            DefaultTableModel modelo = (DefaultTableModel) this.tablaListaAjustes.getModel();//creando el modela ára llenar los datos al JTableje
            limpiarTabla(tablaListaAjustes);
            estiloTabla(tablaListaAjustes);
            //realizando la consulta para realizar el listado de los datos
            AjusteDao invDao = new AjusteDao();
            List<Object[]> lista = invDao.listarAjustes();//obteniendo el listado del Kardex por Almacen
            Object[] fila = new Object[modelo.getColumnCount()];
            if (lista.size() > 0) 
            {
                for (int i = 0; i < lista.size(); i++) 
                {
                    fila[0] = lista.get(i)[0];//id
                    fila[1] = lista.get(i)[1];//fecha
                    fila[2] = lista.get(i)[2];//detalle
                    fila[3] = lista.get(i)[3];//responsable
                    
                    fila[4] = lista.get(i)[4];//producto
//                    fila[5] = Double.parseDouble((String) lista.get(i)[5]);//precio
//                    Double subtotal = Double.parseDouble((String) lista.get(i)[2]) * Double.parseDouble((String) lista.get(i)[5]);//subtotal
//                    fila[6] = Operaciones.redondear(subtotal);
                    modelo.addRow(fila);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El almacen seleccionado no tiene productos..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar los datos del Almacen " + e.getMessage(), "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }

    //Metodo que limpia los elementos de la tabla
    public void limpiarTabla(JTable tabla) {
        try 
        {
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            int filas = tabla.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaAjustes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbmAlmacen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbmStockInicial = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbmPrecioInicial = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbmStockAjuste = new javax.swing.JLabel();
        lbmPrecioAjuste = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Listado de ajustes..");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaListaAjustes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaListaAjustes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "FECHA AJUSTE", "MOTIVO", "RESPONSABLE", "PRODUCTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListaAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaListaAjustesMousePressed(evt);
            }
        });
        tablaListaAjustes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablaListaAjustesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListaAjustes);
        if (tablaListaAjustes.getColumnModel().getColumnCount() > 0) {
            tablaListaAjustes.getColumnModel().getColumn(0).setMinWidth(50);
            tablaListaAjustes.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaListaAjustes.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle Ajuste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 18))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Almacen:");

        lbmAlmacen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbmAlmacen.setForeground(new java.awt.Color(0, 51, 153));
        lbmAlmacen.setText("XXXXXXXXXXX");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Stock inicial:");

        lbmStockInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbmStockInicial.setForeground(new java.awt.Color(0, 102, 102));
        lbmStockInicial.setText("XXXXXXXXXXXX");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Precio inicial:");

        lbmPrecioInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbmPrecioInicial.setForeground(new java.awt.Color(0, 102, 102));
        lbmPrecioInicial.setText("XXXXXXXXXXXX");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Precio ajuste:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Stock ajuste:");

        lbmStockAjuste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbmStockAjuste.setForeground(new java.awt.Color(51, 102, 0));
        lbmStockAjuste.setText("XXXXXXXXXXX");

        lbmPrecioAjuste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbmPrecioAjuste.setForeground(new java.awt.Color(51, 102, 0));
        lbmPrecioAjuste.setText("XXXXXXXXXXX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lbmPrecioInicial))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbmAlmacen)
                            .addComponent(lbmStockInicial))))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbmPrecioAjuste))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbmStockAjuste)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lbmAlmacen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbmStockInicial)
                    .addComponent(jLabel7)
                    .addComponent(lbmStockAjuste))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbmPrecioInicial)
                    .addComponent(jLabel11)
                    .addComponent(lbmPrecioAjuste))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/cancelar.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(5, 5, 5))
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTADO DE AJUSTES A INVENTARIO");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajustes.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaListaAjustesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaListaAjustesKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tablaListaAjustesKeyTyped

    private void tablaListaAjustesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListaAjustesMousePressed
        // TODO add your handling code here:
        try 
        {
            AjusteDao invDao = new AjusteDao();
            List<Object[]> lista = invDao.listarAjustesCompleto(Integer.parseInt(String.valueOf(tablaListaAjustes.getValueAt(tablaListaAjustes.getSelectedRow(), 0))));
            if (lista.size() > 0) 
            {
                for (int i = 0; i < lista.size(); i++) 
                {
                  lbmAlmacen.setText(String.valueOf(lista.get(i)[9]));//nombre almacen
                  lbmStockInicial.setText(String.valueOf(lista.get(i)[5]));//stock inicial
                  lbmStockAjuste.setText(String.valueOf(lista.get(i)[6]));//
                  lbmPrecioInicial.setText(String.valueOf(lista.get(i)[7]));
                  lbmPrecioAjuste.setText(String.valueOf(lista.get(i)[8]));
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "No se encuentra el detalle asociado al ajuste..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al recuperar los datos del Almacen " + ex.getMessage(), "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tablaListaAjustesMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        validaVentana=null;
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbmAlmacen;
    private javax.swing.JLabel lbmPrecioAjuste;
    private javax.swing.JLabel lbmPrecioInicial;
    private javax.swing.JLabel lbmStockAjuste;
    private javax.swing.JLabel lbmStockInicial;
    private javax.swing.JTable tablaListaAjustes;
    // End of variables declaration//GEN-END:variables
}
