/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ventas;

import dao.InventarioDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import view.vtnPrincipal;

/**
 *
 * @author Ing. Reynaldo Rios
 * RWebDesigners
 * Todos los derechos reservados de autor
 * La Paz Bolvia - 2016
 */
public class vtnAddProductoListaPrecios extends javax.swing.JInternalFrame {

    /**
     * Creates new form vtnAddProductoListaPrecios
     */
    public static String validaVentana;// variable que valida que la ventana no se habra mas de una vez

    public vtnAddProductoListaPrecios(int idAlm) {
        initComponents();
        validaVentana = "x";
        /*Poniendo el JinternalFrame al centro de la ventana*/
        int a = vtnPrincipal.sysMDI.getWidth() - this.getWidth();
        int b = vtnPrincipal.sysMDI.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);
        /*fin-----*/
        cargarTabla(idAlm);

    }
    
    //Metodo que realiza el listado de los datos en un JTable de java
    public void cargarTabla(int idAlmacen) 
    {
        try 
        {
            DefaultTableModel modelo = (DefaultTableModel) this.tablaAddProducto.getModel();//creando el modela ára llenar los datos al JTableje
            limpiarTabla(tablaAddProducto);
            //realizando la consulta para realizar el listado de los datos
            InventarioDao invDao = new InventarioDao();
            List<Object[]> lista = invDao.kardexInventarioAlmacen(idAlmacen);//obteniendo el listado del Kardex por Almacen
            Object[] fila = new Object[modelo.getColumnCount()];
            if (lista.size() > 0) 
            {
                for (int i = 0; i < lista.size(); i++) {
                    fila[0] = lista.get(i)[5];//Idproducto
                    fila[1] = lista.get(i)[1];//nombre producto
                 
                    modelo.addRow(fila);
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "El almacen seleccionado no tiene productos..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar información del Almacen " + e.getMessage(), "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }

    //metodo que realiza el limpiado de la tabla
    public void limpiarTabla(JTable tabla) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            int filas = tabla.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    
    //Metodo que verifica si el item seleccionado esta repetido en la tabla
    public boolean buscarRepetidos(int id) 
    {
        DefaultTableModel modelo = (DefaultTableModel) vtnDefinicionPrecios.tablaProductosPrecio.getModel();//recuperando la tabla OC
        for (int i = 0; i < modelo.getRowCount(); i++) 
        {
            if (Integer.parseInt((String) vtnDefinicionPrecios.tablaProductosPrecio.getValueAt(i, 0)) == id)
            {
                return true;
            }
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAddProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPrecioProdLista = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADICIONAR PRODUCTO");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addproductos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(19, 19, 19))
        );

        tablaAddProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO"
            }
        ));
        jScrollPane1.setViewportView(tablaAddProducto);
        if (tablaAddProducto.getColumnModel().getColumnCount() > 0) {
            tablaAddProducto.getColumnModel().getColumn(0).setMinWidth(50);
            tablaAddProducto.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaAddProducto.getColumnModel().getColumn(0).setMaxWidth(55);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Precio:");

        txtPrecioProdLista.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        txtPrecioProdLista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioProdLista.setText("0.0");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/agregar.png"))); // NOI18N
        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioProdLista, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrecioProdLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        validaVentana = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try 
        {
            if (tablaAddProducto.getSelectedRows().length != 0) 
            {
                DefaultTableModel modelo = (DefaultTableModel) vtnDefinicionPrecios.tablaProductosPrecio.getModel();//creando el modelo pára llenar los datos al JTableje
                //realizando la consulta para realizar el listado de los datos
                Object[] fila = new Object[modelo.getColumnCount()];
                //String valor = String.valueOf(tablaAdicionarPro.getValueAt(tablaAdicionarPro.getSelectedRow(), 2));//precio
                double valor = Double.parseDouble(txtPrecioProdLista.getText());//recuperando el precio
                if (valor>0) 
                {
                    
                    int idbuscar = Integer.parseInt(String.valueOf(tablaAddProducto.getValueAt(tablaAddProducto.getSelectedRow(), 0)));

                    if (!buscarRepetidos(idbuscar)) 
                    {
                        fila[0] = String.valueOf(tablaAddProducto.getValueAt(tablaAddProducto.getSelectedRow(), 0));//ID PRODUCTO
                        fila[1] = String.valueOf(tablaAddProducto.getValueAt(tablaAddProducto.getSelectedRow(), 1));//producto
                        fila[2]=String.valueOf(valor);
                        modelo.addRow(fila);//adicionando la fila a la tabla
                        this.dispose();
                        validaVentana = null;
                    } 
                    else 
                    {
                        JOptionPane.showMessageDialog(null, "El producto ya fue añadido..!!", "Mensaje...", JOptionPane.ERROR_MESSAGE);
                    }
                } 
                else 
                {
                    JOptionPane.showMessageDialog(null, "El precio no puede ser 0 ", "Mensaje..", JOptionPane.WARNING_MESSAGE);
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Seleccione un producto ", "Mensaje..", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage(), "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAddProducto;
    private javax.swing.JTextField txtPrecioProdLista;
    // End of variables declaration//GEN-END:variables
}
