/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ventas;

import dao.AlmacenDao;
import dao.ListaPreciosDao;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import mapeos.Almacen;
import mapeos.ListaPrecios;
import mapeos.Productos_lista_precios;
import util.Validaciones;
import view.vtnPrincipal;

/**
 *
 * @author Reynaldo
 */
public class vtnDefinicionPrecios extends javax.swing.JInternalFrame {

    /**
     * Creates new form vtnDefinicionPrecios
     */
    public static String validaVentana;// variable que valida que la ventana no se habra mas de una vez

    public vtnDefinicionPrecios() {
        initComponents();
        validaVentana = "x";//insertando un valor a la variable que valida a la ventana
        /*Poniendo el JinternalFrame al centro de la ventana*/
        int a = vtnPrincipal.sysMDI.getWidth() - this.getWidth();
        int b = vtnPrincipal.sysMDI.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);
        /*fin-----*/
        cargarAlmacen();
        listarPrecios();
        
    }

    //Metodo que carga los elementos del almacen
    public void cargarAlmacen() {
        try {
            AlmacenDao almDao = new AlmacenDao();
            List<Almacen> lista = almDao.listarAlmacen();
            if (lista.size() != 0) {
                for (int i = 0; i < lista.size(); i++) {
                    comboAlmacenPrecios.addItem(lista.get(i).getNombre());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe tener por lo menos un almacen registrado..!! ", "Mensaje", JOptionPane.ERROR_MESSAGE);
                comboAlmacenPrecios.setEnabled(false);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //Metodo que realiza el listado de las listas de precios 
    public void listarPrecios() 
    {
        try 
        {
            DefaultTableModel modelo = (DefaultTableModel) this.tablaListaPrecios.getModel();//creando el modela ára llenar los datos al JTableje
            limpiarTabla(tablaListaPrecios);
            //realizando la consulta para realizar el listado de los datos
            ListaPreciosDao liDao = new ListaPreciosDao();
            List<Object[]> lista = liDao.listarPrecios();
            if (lista.size() > 0) 
            {
                Object[] fila = new Object[modelo.getColumnCount()];
                TableColumnModel columnModel = tablaListaPrecios.getColumnModel();
                boolean pivote = false;
                for (int i = 0; i < lista.size(); i++) 
                {
                    //columnModel.getColumn(i).setPreferredWidth(20);
                    fila[0] = lista.get(i)[0];//idlista_precios
                    fila[1] = lista.get(i)[1];//fecha
                    fila[2] = lista.get(i)[2];//nombre
                    fila[3] = lista.get(i)[3];//codigo 
                    fila[4] = lista.get(i)[4];//estado
                    fila[5] = lista.get(i)[5];//Almacen
//                    fila[6] = lista.get(i)[6];//precio Estado
                    modelo.addRow(fila);

                }

            } else {
                JOptionPane.showMessageDialog(null, "No tiene lista de precios creado..!! ", "Mensaje", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error---->" + e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }
    //metodo que realiza el limpiado de la tabla
    public void limpiarTabla(JTable tabla) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            int filas = tabla.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtListaNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txCodigoLista = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboAlmacenPrecios = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductosPrecio = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboEstadoLPrecio = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaListaPrecios = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        detalleListaPrecios = new javax.swing.JTable();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DEFINICIÓN DE PRECIOS DE VENTA");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ventas2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Nombre:");

        txtListaNombre.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        txtListaNombre.setToolTipText("Nombre de la lista de precios");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Codigo:");

        txCodigoLista.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        txCodigoLista.setToolTipText("Codigo asociado a la lista de precios");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Almacen:");

        comboAlmacenPrecios.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        comboAlmacenPrecios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------------------" }));

        tablaProductosPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "PRECIO MERCADO", "PRECIO CLIENTE", "PRECIO MAYORISTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProductosPrecio);
        if (tablaProductosPrecio.getColumnModel().getColumnCount() > 0) {
            tablaProductosPrecio.getColumnModel().getColumn(0).setMinWidth(50);
            tablaProductosPrecio.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaProductosPrecio.getColumnModel().getColumn(0).setMaxWidth(55);
            tablaProductosPrecio.getColumnModel().getColumn(2).setMinWidth(120);
            tablaProductosPrecio.getColumnModel().getColumn(2).setPreferredWidth(120);
            tablaProductosPrecio.getColumnModel().getColumn(2).setMaxWidth(120);
            tablaProductosPrecio.getColumnModel().getColumn(3).setMinWidth(120);
            tablaProductosPrecio.getColumnModel().getColumn(3).setPreferredWidth(120);
            tablaProductosPrecio.getColumnModel().getColumn(3).setMaxWidth(120);
            tablaProductosPrecio.getColumnModel().getColumn(4).setMinWidth(120);
            tablaProductosPrecio.getColumnModel().getColumn(4).setPreferredWidth(120);
            tablaProductosPrecio.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Producto:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/View.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Estado:");

        comboEstadoLPrecio.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        comboEstadoLPrecio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysInventory/iconos/guardar.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboAlmacenPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtListaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txCodigoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(comboEstadoLPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtListaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txCodigoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(comboEstadoLPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboAlmacenPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Definir lista", jPanel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("LISTA DE PRECIOS CREADOS");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("PRODUCTOS Y PRECIOS ESTABLECIDOS");

        tablaListaPrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "F. CREACIÓN", "NOMBRE", "CODIGO", "ESTADO", "ALMACEN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListaPrecios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaListaPreciosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaListaPrecios);
        if (tablaListaPrecios.getColumnModel().getColumnCount() > 0) {
            tablaListaPrecios.getColumnModel().getColumn(0).setMinWidth(50);
            tablaListaPrecios.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaListaPrecios.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        detalleListaPrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "PRODUCTO", "PRECIO MERCADO", "PRECIO CLIENTE", "PRECIO MAYORISTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(detalleListaPrecios);
        if (detalleListaPrecios.getColumnModel().getColumnCount() > 0) {
            detalleListaPrecios.getColumnModel().getColumn(0).setMinWidth(50);
            detalleListaPrecios.getColumnModel().getColumn(0).setPreferredWidth(50);
            detalleListaPrecios.getColumnModel().getColumn(0).setMaxWidth(50);
            detalleListaPrecios.getColumnModel().getColumn(1).setMinWidth(280);
            detalleListaPrecios.getColumnModel().getColumn(1).setPreferredWidth(280);
            detalleListaPrecios.getColumnModel().getColumn(1).setMaxWidth(280);
            detalleListaPrecios.getColumnModel().getColumn(2).setMinWidth(120);
            detalleListaPrecios.getColumnModel().getColumn(2).setPreferredWidth(120);
            detalleListaPrecios.getColumnModel().getColumn(2).setMaxWidth(120);
            detalleListaPrecios.getColumnModel().getColumn(3).setMinWidth(120);
            detalleListaPrecios.getColumnModel().getColumn(3).setPreferredWidth(120);
            detalleListaPrecios.getColumnModel().getColumn(3).setMaxWidth(120);
            detalleListaPrecios.getColumnModel().getColumn(4).setMinWidth(120);
            detalleListaPrecios.getColumnModel().getColumn(4).setPreferredWidth(120);
            detalleListaPrecios.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel9)))
                        .addGap(0, 239, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar precios", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        validaVentana = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String varValicadion = vtnAddProductoListaPrecios.validaVentana;//recuperando el valor de la variable de validacion de la ventana
        if (varValicadion == null) {
            try {
                if (comboAlmacenPrecios.getSelectedIndex() > 0) 
                {
                    AlmacenDao almDao = new AlmacenDao();
                    int idAlmacen = almDao.buscarAlmacenId(comboAlmacenPrecios.getSelectedItem().toString());
                    //JOptionPane.showMessageDialog(this, "--->"+idAlmacen);

                    vtnAddProductoListaPrecios listaPro = new vtnAddProductoListaPrecios(idAlmacen);

                    vtnPrincipal.sysMDI.add(listaPro);
                    listaPro.setClosable(true);//si se puede cerra la ventana
                    listaPro.setTitle("Seleccione un producto");
                    //listaPro.setLocationRelativeTo(null);

                    listaPro.setVisible(true);
                } 
                else 
                {
                    JOptionPane.showMessageDialog(this, "Seleccione un Almacen", "Mensaje", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "La ventana de adicionar productos ya esta activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            //Realizando la validacion de los campos de ingreso
            List<String> validar = new ArrayList<>();
            validar.add(txtListaNombre.getText());
            validar.add(txCodigoLista.getText());
            if (Validaciones.validarCampos(validar)) 
            {
                ListaPrecios listaPrecios = new ListaPrecios();
                listaPrecios.setNombre(txtListaNombre.getText());//insertando el nombre
                listaPrecios.setCodigo(txCodigoLista.getText());//seteando el codigo

                listaPrecios.setEstado(comboEstadoLPrecio.getSelectedItem().toString());//Seteando el estado
                AlmacenDao almDao = new AlmacenDao();
                int idAlm = almDao.buscarAlmacenId(comboAlmacenPrecios.getSelectedItem().toString());
                listaPrecios.setIdAlmacen(idAlm);//seteando el id del almacen al que pertenece la lista de precios
                //JOptionPane.showMessageDialog(this,"-->"+idAlm);
                //RECUPERANDO EL DETALLE DE LOS ITEMS SELECCIONADOS EN LA TABLA LISTA DE PRECIOS
                Set<Productos_lista_precios> items = new HashSet<>();
                for (int i = 0; i < tablaProductosPrecio.getRowCount(); i++) 
                {
                    Productos_lista_precios det = new Productos_lista_precios();
                    det.setIdProducto(Integer.parseInt(String.valueOf(tablaProductosPrecio.getValueAt(i, 0))));
                    det.setPrecio(String.valueOf(tablaProductosPrecio.getValueAt(i, 2)));
                    det.setPrecioCliente(String.valueOf(tablaProductosPrecio.getValueAt(i, 3)));
                    det.setPrecioMayor(String.valueOf(tablaProductosPrecio.getValueAt(i, 4)));
                    
                    det.setListaPrecios(listaPrecios);
                    items.add(det);
                }
                listaPrecios.setListaProductos(items);//adicionando el detalle de la lista de precios

                //Verificando si la tabla tiene almenos un item a registrar
                if (tablaProductosPrecio.getRowCount() > 0) 
                {
                    ListaPreciosDao lpDao = new ListaPreciosDao();
                    if (lpDao.BuscarNombre(txtListaNombre.getText()) == null) 
                    {
                        if (lpDao.BuscarCodigo(txCodigoLista.getText())==null)
                        {
                            if (lpDao.registarListaPrecios(listaPrecios)) 
                            {
                                JOptionPane.showMessageDialog(this, "Registro de lista de precios correcto.", "Mensaje..", JOptionPane.INFORMATION_MESSAGE);
                                limpiarTabla(tablaProductosPrecio);
                                listarPrecios();
                                txtListaNombre.setText("");
                                txCodigoLista.setText("");
                            }
                        } 
                        else 
                        {
                            JOptionPane.showMessageDialog(this, "El CODIGO ingresado ya se encuentra registrado", "Nombre duplicado", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "El nombre ingresado ya se encuentra registrado", "Nombre duplicado", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Adicione un producto(s) a comprar..!!", "Mensaje..", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Faltan campos por llenar", "Mensaje", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar lista de precios..", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaListaPreciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListaPreciosMousePressed
        // TODO add your handling code here:
          try 
        {
            DefaultTableModel modelo = (DefaultTableModel) tablaListaPrecios.getModel();//creando el modelo pára llenar los datos al JTableje
            int idListaPrecios = Integer.parseInt(String.valueOf(tablaListaPrecios.getValueAt(tablaListaPrecios.getSelectedRow(), 0)));//recuperando el id del combo
            ListaPreciosDao liDao = new ListaPreciosDao();
            List<Object[]> detalle = liDao.listarItemsListaPrecios(idListaPrecios);

            DefaultTableModel modelodetalle = (DefaultTableModel) detalleListaPrecios.getModel();//creando el modelo pára llenar los datos al JTableje
            Object[] fila = new Object[modelodetalle.getColumnCount()];
            limpiarTabla(detalleListaPrecios);
            for (int i = 0; i < detalle.size(); i++) 
            {
                // JOptionPane.showMessageDialog(rootPane, "DIM-->" + i);
                fila[0] = detalle.get(i)[0];//id
                fila[1] = detalle.get(i)[1];//nombre
                fila[2] = detalle.get(i)[2];//precio mercado
                fila[3] = detalle.get(i)[3];//precio cliente
                fila[4] = detalle.get(i)[4];//precio Mayorista
                
                modelodetalle.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar el detalle de la compra " + e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tablaListaPreciosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboAlmacenPrecios;
    private javax.swing.JComboBox comboEstadoLPrecio;
    private javax.swing.JTable detalleListaPrecios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaListaPrecios;
    public static javax.swing.JTable tablaProductosPrecio;
    private javax.swing.JTextField txCodigoLista;
    private javax.swing.JTextField txtListaNombre;
    // End of variables declaration//GEN-END:variables
}
