package mapeos;
// Generated 10-02-2016 05:32:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String nombre;
     private String apellido;
     private String ci;
     private String telefono;
     private String nrocliente;
     private String correo;
     private String direccion;
     private Set facturas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String nombre, String apellido, String ci, String telefono, String nrocliente, String correo, String direccion, Set facturas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.ci = ci;
       this.telefono = telefono;
       this.nrocliente = nrocliente;
       this.correo = correo;
       this.direccion = direccion;
       this.facturas = facturas;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getNrocliente() {
        return this.nrocliente;
    }
    
    public void setNrocliente(String nrocliente) {
        this.nrocliente = nrocliente;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


