package mapeos;
// Generated 10-02-2016 05:32:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idfactura;
     private Cliente cliente;
     private String nrofactura;
     private String codigocliente;
     private String nrocliente;
     private String subtotal;
     private String iva;
     private String total;
     private String fechafactura;
     private Set detallefacturas = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Cliente cliente) {
        this.cliente = cliente;
    }
    public Factura(Cliente cliente, String nrofactura, String codigocliente, String nrocliente, String subtotal, String iva, String total, String fechafactura, Set detallefacturas) {
       this.cliente = cliente;
       this.nrofactura = nrofactura;
       this.codigocliente = codigocliente;
       this.nrocliente = nrocliente;
       this.subtotal = subtotal;
       this.iva = iva;
       this.total = total;
       this.fechafactura = fechafactura;
       this.detallefacturas = detallefacturas;
    }
   
    public Integer getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(Integer idfactura) {
        this.idfactura = idfactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getNrofactura() {
        return this.nrofactura;
    }
    
    public void setNrofactura(String nrofactura) {
        this.nrofactura = nrofactura;
    }
    public String getCodigocliente() {
        return this.codigocliente;
    }
    
    public void setCodigocliente(String codigocliente) {
        this.codigocliente = codigocliente;
    }
    public String getNrocliente() {
        return this.nrocliente;
    }
    
    public void setNrocliente(String nrocliente) {
        this.nrocliente = nrocliente;
    }
    public String getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(String subtotal) {
        this.subtotal = subtotal;
    }
    public String getIva() {
        return this.iva;
    }
    
    public void setIva(String iva) {
        this.iva = iva;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public String getFechafactura() {
        return this.fechafactura;
    }
    
    public void setFechafactura(String fechafactura) {
        this.fechafactura = fechafactura;
    }
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


