package mapeos;
// Generated 10-02-2016 05:32:08 PM by Hibernate Tools 3.6.0

/**
 * Fifo generated by hbm2java
 */
public class Fifo implements java.io.Serializable {

    private Integer idfifo;
    private Inventario inventario;
    private String fecha;
    private String detalle;
    private int cant_entrada;
    private String precio_entrada;
    private String p_total_entrada;
    private int cant_salida;
    private String precio_salida;
    private String p_total_salida;
    private int cant_saldo;
    private String precio_saldo;
    private String p_total_saldo;

    private String documento;
    private int ndocumento;

    public Fifo() {
    }

    public Fifo(Inventario inventario, String fecha, String detalle, int cant_entrada, String precio_entrada, int cant_salida, String precio_salida) {
        this.inventario = inventario;
        this.fecha = fecha;
        this.detalle = detalle;
        this.cant_entrada = cant_entrada;
        this.precio_entrada = precio_entrada;
        this.cant_salida = cant_salida;
        this.precio_salida = precio_salida;
    }

    public Integer getIdfifo() {
        return idfifo;
    }

    public void setIdfifo(Integer idfifo) {
        this.idfifo = idfifo;
    }

    public Inventario getInventario() {
        return inventario;
    }

    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getDetalle() {
        return detalle;
    }

    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    public int getCant_entrada() {
        return cant_entrada;
    }

    public void setCant_entrada(int cant_entrada) {
        this.cant_entrada = cant_entrada;
    }

    public String getPrecio_entrada() {
        return precio_entrada;
    }

    public void setPrecio_entrada(String precio_entrada) {
        this.precio_entrada = precio_entrada;
    }

    public int getCant_salida() {
        return cant_salida;
    }

    public void setCant_salida(int cant_salida) {
        this.cant_salida = cant_salida;
    }

    public String getPrecio_salida() {
        return precio_salida;
    }

    public void setPrecio_salida(String precio_salida) {
        this.precio_salida = precio_salida;
    }

    public String getDocumento() {
        return documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    public int getNdocumento() {
        return ndocumento;
    }

    public void setNdocumento(int ndocumento) {
        this.ndocumento = ndocumento;
    }

    public String getP_total_entrada() {
        return p_total_entrada;
    }

    public void setP_total_entrada(String p_total_entrada) {
        this.p_total_entrada = p_total_entrada;
    }

    public String getP_total_salida() {
        return p_total_salida;
    }

    public void setP_total_salida(String p_total_salida) {
        this.p_total_salida = p_total_salida;
    }

    public String getP_total_saldo() {
        return p_total_saldo;
    }

    public void setP_total_saldo(String p_total_saldo) {
        this.p_total_saldo = p_total_saldo;
    }

    public int getCant_saldo() {
        return cant_saldo;
    }

    public void setCant_saldo(int cant_saldo) {
        this.cant_saldo = cant_saldo;
    }

    public String getPrecio_saldo() {
        return precio_saldo;
    }

    public void setPrecio_saldo(String precio_saldo) {
        this.precio_saldo = precio_saldo;
    }

}
