package mapeos;
// Generated 10-02-2016 05:32:08 PM by Hibernate Tools 3.6.0



/**
 * Informacion generated by hbm2java
 */
public class Informacion  implements java.io.Serializable {


     private Integer idinformacion;
     private String razonsocial;
     private String nit;
     private String direccion;
     private String telefono;
     private String ciudad;
     private String email;
     private String fax;
     private byte[] logo;
     private String web;

    public Informacion() {
    }

    public Informacion(String razonsocial, String nit, String direccion, String telefono, String ciudad, String email, String fax, byte[] logo, String web) {
       this.razonsocial = razonsocial;
       this.nit = nit;
       this.direccion = direccion;
       this.telefono = telefono;
       this.ciudad = ciudad;
       this.email = email;
       this.fax = fax;
       this.logo = logo;
       this.web = web;
    }
   
    public Integer getIdinformacion() {
        return this.idinformacion;
    }
    
    public void setIdinformacion(Integer idinformacion) {
        this.idinformacion = idinformacion;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }




}


