package mapeos;
// Generated 10-02-2016 05:32:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Privilegio generated by hbm2java
 */
public class Privilegio  implements java.io.Serializable {


     private Integer idprivilegio;
     private String nombre;
     private Usuario usuario;
 

    public Privilegio() {
    }

   
    public Integer getIdprivilegio() {
        return this.idprivilegio;
    }
    
    public void setIdprivilegio(Integer idprivilegio) {
        this.idprivilegio = idprivilegio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}


