package mapeos;
// Generated 10-02-2016 05:32:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable 
{
     private Integer idproducto;
     private Categoria categoria;
     private Proveedor proveedor;
     private UnidadMedida unidadMedida;
     private String nombre;
     private String descripcion;
     private String marca;
     private String precio;
     private String codigoproducto;
     private String estado;
     private byte[] imagen;
     private int stockMinimo;
     private int stockMaximo;
   
     private Set inventarios = new HashSet(0);
     private Set detallefacturas = new HashSet(0);
     private Set detallecompra = new HashSet(0);
     

    public Producto() {
    }

    public Producto(Categoria categoria, String nombre, String descripcion, String marca, String codigoproducto, String estado, byte[] imagen) {
        this.categoria = categoria;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.marca = marca;
        this.codigoproducto = codigoproducto;
        this.estado = estado;
        this.imagen = imagen;
    }

    
    public Producto(Categoria categoria) {
        this.categoria = categoria;
    }
    
   
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getCodigoproducto() {
        return this.codigoproducto;
    }
    
    public void setCodigoproducto(String codigoproducto) {
        this.codigoproducto = codigoproducto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }

    public Proveedor getProveedor() {
        return proveedor;
    }

    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    public String getPrecio() {
        return precio;
    }

    public void setPrecio(String precio) {
        this.precio = precio;
    }

    public Set getDetallecompra() {
        return detallecompra;
    }

    public void setDetallecompra(Set detallecompra) {
        this.detallecompra = detallecompra;
    }

    public int getStockMinimo() {
        return stockMinimo;
    }

    public void setStockMinimo(int stockMinimo) {
        this.stockMinimo = stockMinimo;
    }

    public int getStockMaximo() {
        return stockMaximo;
    }

    public void setStockMaximo(int stockMaximo) {
        this.stockMaximo = stockMaximo;
    }

    public UnidadMedida getUnidadMedida() {
        return unidadMedida;
    }

    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
}


