package mapeos;
// Generated 10-02-2016 05:32:08 PM by Hibernate Tools 3.6.0



/**
 * Reservas generated by hbm2java
 */
public class Reservas  implements java.io.Serializable {


     private Integer idreservas;
     private Inventario inventario;
     private String estado;
     private String solicitante;
     private String observaciones;
     private String cantidad;
     private String fecha;
     private String limitereserva;

    public Reservas() {
    }

	
    public Reservas(Inventario inventario) {
        this.inventario = inventario;
    }
    public Reservas(Inventario inventario, String estado, String solicitante, String observaciones, String cantidad, String fecha, String limitereserva) {
       this.inventario = inventario;
       this.estado = estado;
       this.solicitante = solicitante;
       this.observaciones = observaciones;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.limitereserva = limitereserva;
    }
   
    public Integer getIdreservas() {
        return this.idreservas;
    }
    
    public void setIdreservas(Integer idreservas) {
        this.idreservas = idreservas;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getSolicitante() {
        return this.solicitante;
    }
    
    public void setSolicitante(String solicitante) {
        this.solicitante = solicitante;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getLimitereserva() {
        return this.limitereserva;
    }
    
    public void setLimitereserva(String limitereserva) {
        this.limitereserva = limitereserva;
    }




}


