package mapeos;
// Generated 10-02-2016 05:32:08 PM by Hibernate Tools 3.6.0

import java.util.Set;


/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Integer idusuario;
    private int ci;
    private String nombre;
    private String apellido;
    private String alias;
    private String password;
    private String estado;
    private String cargo;
    private int telefono;
    private byte[] imagen;
    
    private Set<Detallecompra> privilegios;

    public Usuario() {
    }

    public Integer getIdusuario() {
        return this.idusuario;
    }

    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }

    public String getAlias() {
        return this.alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public int getCi() {
        return ci;
    }

    public void setCi(int ci) {
        this.ci = ci;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getCargo() {
        return cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    public int getTelefono() {
        return telefono;
    }

    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

    public byte[] getImagen() {
        return imagen;
    }

    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }

    public Set<Detallecompra> getPrivilegios() {
        return privilegios;
    }

    public void setPrivilegios(Set<Detallecompra> privilegios) {
        this.privilegios = privilegios;
    }
}
